[package]
name = "kzg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
csprng_setup = ["rand", "std"]
std = []

[dependencies]
pairing = "0.20.0"
thiserror = "1.0.26"
rand = { version = "0.8.4", optional = true }

[dev-dependencies]
rand = "0.8.4"