[package]
name = "kzg"
version = "0.0.7"
edition = "2018"
license = "MIT"
description = "a simple implementation of the KZG polynomial commitment scheme"
authors = [ "sladuca777@gmail.com" ]
repository = "https://github.com/Sladuca/kzg"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
csprng_setup = ["rand", "std"]
std = []

[dependencies]
pairing = "0.20.0"
thiserror = "1.0.26"
rand = { version = "0.8.4", optional = true }

[dev-dependencies]
rand = "0.8.4"
